// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOAivhuoEoyJpcKyfzONTmZPc2_GDcdI4',
    appId: '1:262987721526:web:9fe127ad1861a21e0e2197',
    messagingSenderId: '262987721526',
    projectId: 'club-atlhetica',
    authDomain: 'club-atlhetica.firebaseapp.com',
    storageBucket: 'club-atlhetica.appspot.com',
    measurementId: 'G-5C90WT9025',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWS68HINrBu3P8ku5yQmIqRcBjIn-kGak',
    appId: '1:262987721526:android:c54fb323e75115e30e2197',
    messagingSenderId: '262987721526',
    projectId: 'club-atlhetica',
    storageBucket: 'club-atlhetica.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvv4b7KyAlAQwzNJ29vv82aUR_9BBwi_Y',
    appId: '1:262987721526:ios:f916af9f5d60ae150e2197',
    messagingSenderId: '262987721526',
    projectId: 'club-atlhetica',
    storageBucket: 'club-atlhetica.appspot.com',
    iosClientId: '262987721526-ho8jhaclq136g8uubi5cb8a5o0j83u97.apps.googleusercontent.com',
    iosBundleId: 'com.example.clubAtlhetica',
  );
}
